sudo: required
dist: trusty

language: java
jdk:
- oraclejdk8

cache:
  directories:
  - $HOME/.m2/repository

install:
  # Override default travis to use the maven wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - ./travis.sh

branches:
  except:
    - /^[0-9]/

env:
  global:
  - secure: "fDFNVRXEWVPfOUoeYR3SCH9NtnCCSRapeXHsvWx5Hxiwx0KvYxJ32WpFt6VJ0bbxSOJaZGKuHq34xtDZK8rXt5gJB7xkCtH9q3uPoZbxQvgdtXKBcqsIRc9YkdtBKTk86eW8XvwxiNxb8rIVN8haMfjvoL65j9Jm18+hHEeleQfzCqxLDAp0YHfGL2ixdqLz0BF4pL0hDHywqZOD8EMwp8O3h2jZ9uTzchmMIfGiFqlDW7eSU64QX3rGzikkpknzh4fSm1GOeFRLwfPKk/+AL3PDTQMFZf8mulJ0+k2iClg3Li7d57TQZS+uIx/ogbkHB+ArpHWIbYVHOgIRi6BDeVP7j9TZ/AaXBDQIpSL/210JiJR794SaKMCWsADsXviiVSET+Aq9sZ254QhdhFS5utQ+MOcbLuxI2VNDZuNxJ5sn2w6DXzGLPhue9CXlv8rJuHSYrSZIyt9fXIl/nf9hAkZjYKAs2mzYvMyXjhj5YcrywyZ5r33LKuaoEGzciF0lKlw+1222hs9N3tRkqjdsxon3oKogUyVpYz0tNacUGHaemTU9CG9qU1N8my6FzcjHJ7TxigtC0bs5j6pVTxjdlIIBuWUjyYDOGYf4IdHuSKWDdqX/GvcLmewEqicGXY3pOlehPwCC8DXhhz0s1jbk3AolvWa7D6FkFKSILFTKErg="
  - secure: "VL7rGIopCdqQyYiPxG3+W0Bm2Cpgkjc/Q21WeTxZDWRnUROBu25UnY7IC9cPKnQkVx0Mfso9QqRQ5slA5qYF/7J/4zW4tpdFIvjhks3kXpAcXQdI8L9ZOTmEsAN2tbDcbSuHbtDHoy1limerRtaxMkGiGU08swQpu5RSHQJG5lzmQWDRVw4VHV8KmB1cG+IgH/u2uJoqJViCXlABIgjVRjawuPxtLWXb5xsbv75VaaRgP5vlT3fYThTvGEbNwE4t2tEabORwpbKbICi0Rw9NWWe5gUII3XLy0P/9KRzQBDuNDMVtHWP2TbokdRixETYyCELCtO0BbbtLL1Al6SM5pkr8lIRG5fjp27SO6HU4Ndi7NK47CJmwCUr/bFmPVNaDI5p1C7PenVvw11kUYTB+YusmyDL/y59RH7GjWpVvYuqh1O6o92TWbkr/vk9t+REZIxnAEvYpVLoDsJwDNrzQw2rXbdTtiBOX3kvYV8HUlSyqQcSE9O4KeXGG1UnsYqUVSlJENgWvOa7OI8Ni+X30NHxwEu5kbm9VE8r/24xb5CM6SacTVa7LVh1E+eDwCjCy0FuvlaHkqBTArEdTkq5jK8VmhdE81BfSj7I2xAY20VE3VLAz0cwd7DYx/eQ82wbG2Ae4XY7CNlXOcvJ4Z11dGnasn1ZE+2zXjusiQqGFJvI="