sudo: required
dist: trusty

language: java
jdk:
- oraclejdk8

cache:
  directories:
  - $HOME/.m2/repository

before_install:
  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

install:
  # Override default travis to use the maven wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - ./travis.sh

branches:
  except:
    - /^[0-9]/

env:
  global:
  - secure: "fDFNVRXEWVPfOUoeYR3SCH9NtnCCSRapeXHsvWx5Hxiwx0KvYxJ32WpFt6VJ0bbxSOJaZGKuHq34xtDZK8rXt5gJB7xkCtH9q3uPoZbxQvgdtXKBcqsIRc9YkdtBKTk86eW8XvwxiNxb8rIVN8haMfjvoL65j9Jm18+hHEeleQfzCqxLDAp0YHfGL2ixdqLz0BF4pL0hDHywqZOD8EMwp8O3h2jZ9uTzchmMIfGiFqlDW7eSU64QX3rGzikkpknzh4fSm1GOeFRLwfPKk/+AL3PDTQMFZf8mulJ0+k2iClg3Li7d57TQZS+uIx/ogbkHB+ArpHWIbYVHOgIRi6BDeVP7j9TZ/AaXBDQIpSL/210JiJR794SaKMCWsADsXviiVSET+Aq9sZ254QhdhFS5utQ+MOcbLuxI2VNDZuNxJ5sn2w6DXzGLPhue9CXlv8rJuHSYrSZIyt9fXIl/nf9hAkZjYKAs2mzYvMyXjhj5YcrywyZ5r33LKuaoEGzciF0lKlw+1222hs9N3tRkqjdsxon3oKogUyVpYz0tNacUGHaemTU9CG9qU1N8my6FzcjHJ7TxigtC0bs5j6pVTxjdlIIBuWUjyYDOGYf4IdHuSKWDdqX/GvcLmewEqicGXY3pOlehPwCC8DXhhz0s1jbk3AolvWa7D6FkFKSILFTKErg="
  - secure: "VL7rGIopCdqQyYiPxG3+W0Bm2Cpgkjc/Q21WeTxZDWRnUROBu25UnY7IC9cPKnQkVx0Mfso9QqRQ5slA5qYF/7J/4zW4tpdFIvjhks3kXpAcXQdI8L9ZOTmEsAN2tbDcbSuHbtDHoy1limerRtaxMkGiGU08swQpu5RSHQJG5lzmQWDRVw4VHV8KmB1cG+IgH/u2uJoqJViCXlABIgjVRjawuPxtLWXb5xsbv75VaaRgP5vlT3fYThTvGEbNwE4t2tEabORwpbKbICi0Rw9NWWe5gUII3XLy0P/9KRzQBDuNDMVtHWP2TbokdRixETYyCELCtO0BbbtLL1Al6SM5pkr8lIRG5fjp27SO6HU4Ndi7NK47CJmwCUr/bFmPVNaDI5p1C7PenVvw11kUYTB+YusmyDL/y59RH7GjWpVvYuqh1O6o92TWbkr/vk9t+REZIxnAEvYpVLoDsJwDNrzQw2rXbdTtiBOX3kvYV8HUlSyqQcSE9O4KeXGG1UnsYqUVSlJENgWvOa7OI8Ni+X30NHxwEu5kbm9VE8r/24xb5CM6SacTVa7LVh1E+eDwCjCy0FuvlaHkqBTArEdTkq5jK8VmhdE81BfSj7I2xAY20VE3VLAz0cwd7DYx/eQ82wbG2Ae4XY7CNlXOcvJ4Z11dGnasn1ZE+2zXjusiQqGFJvI="
  - secure: "wUVIWZfmwGM6condMpNG8EZyJFOCkoJPG6GnfV1HmJeHNnzjdqSUVkwKF6PbOtp4DlsLfVZqECQHhprGXP6k2g/Sdm3E062MCrdpAF+nvoL6/xoUi4ToHfrns9SJFVBHjjsJaX5AUS9M+OYKUhEESNdFANhh68Un7mqLxMzFw+OW2jImsD275AF/Y4WUHEE9HsntY6Vrjox+aDrOCofZJhxYI1+/NX2wFE75XYFDn8qCCnPihMrC8nOzH8EG5+ARzapj0m4HnRM1G4SsO3lr3adTEAp62erNlfhh+QoMyzOZs+OthP9JeSgMYurckJ6yqBTfChWp1W8mp3FmBHITuXooOemwuUPJxma9hNFbdjH9kzgbUgZcfL24TOD7pazITbu1ylkhJaJRjLPTWLIJ71inXPTyCLMLDKMlDBZEeCQWuyq3iQXpKV+rPIJ+t6WrCYGS50gp6FHAnQ5G/sToAEleS0nKwGYGvSaWDnse675TAc2B6AymnO5juRXttIUMJFmXBFlG0mkaavCvijQsVt6KGyGFsf7Phv0vKCoAoUuYjPJDiQV4uXeidWEr7koLehOeXsbHVh3d5O+C9bmDvIXI3vSZtl/5mSqstYGoH+ZPSbNWr1lRF4b7kFItscCmyFujVvnht/K2WH8v8kwtqXpguBUQbmx7/lpzCFdgOgg="